'''
84 FACA UM PROGRAMA QUE LEIA
NOME E PESO DE VARIAS PESOAS
MOSTRE QUANTAS FORAM CADASTRADAS
AS MAIS PESADAS
AS MAIS LEVES

85 CRIE UM PROGRAMA ONDE O USUARIO CADASTRE 7 VALORES NUMERICOS E DENTRO DESTA LISTA
COLOQUE UMA LISTA COM NUMEROS IMPARES
OUTRA COM VALORES pares
TODAS AS LISTAS DEVEMESTAR ORDENADAS DE FORMA CRESCENTE

86 CRIE UM PROGRAMA QUE CRIE UMA MATRIS 3 X3 E A PREENCHA COM VALORES NUMERICOS
MOSTRE A MATRIZ NA TELA COM A FORMATAÇÃO DE UMA MATRIZ


87 APRIMORE O ANTERIOR MOSTRANDO A
SOMA DOS VALORES PARES
A SOMA DA TERCEIRA COLuNA
 O MAIOR VALOR DA SEGUNDA COLUNA

 88 FACA UM PROGRAMA QUE AJUDDE UM JOGADOR DA MEGA A FAER PALPITES
 NUMERO DE jOGOS A SEREM FEITOS
 SORTEAR NUMEROS DEE 1 A 60 - NAO SE REPITAM
TODAS AS LISTAS ( UMA COM CADA JOGO ) DEVE ESTAR EM UMA LISTA COMPOSTA

89  CRIE UM  PROGRAMA QUE LEIA NOME DOS ALUNOS E DUAS NOTAS PARA CADA
GUARDAR EM UMA LITA COMPOSTA
MOSTRE BOLETIM COM A MEDIA
PERMITA QUE O USUARIO POSSA MOTRAR AS NOTAS DO ANO INDIVIDUALMENTE
UMA LISTA TEM
LISTA  DE ALUNOS
ALUNOS TEM LISTA NOTAS
'''