'''
96 FAÇA M PROGRAMA QUE CHAMA-SE AREA
E CALCULE A AREA DE UM TERRENO - FAZER COM FUNÇÃO CLARO

97 FAÇA UM PROGRAMA UE TENHA O FUNÇÃO CHAMADA ESCREVA QUE RECEBA
 UM TEXTO QUALQUER E PRINT JUNTO A MSG O ENFEITE COM TAMANHO ADAPTAVEL AO TAMANHO DA MSG

 98 FAÇA UM PROGRAMA QUE TENHA UMA FUNÇÃO CHAADA CONTADOR QUE RECEBA TRES PARAMETROS E REALIZE A CONTAGEM
 PARAMETROS SAO; INICIO FIM E SALTO
 FAÇA OS DOIS PRIMEIROS DE FORMA AUTOMATICA POSTERIOR FAÇA UM PERSONALIZADO PERGUNTANDO PARA O USUARIO
 E DEVE FUNCIONAR COM OS TRES;
  DO MENOR PARA MAIOR
 DO MAIOR PARA O MAIOR
 E COM SALTO NEGATIVO
 
 99 DESEMPACOAMENTO E PARMETROS 
 TERA A FUNÇÃO MAIOR 
 REEBERÁ VARIOS PARAMETROS E SERA CAPAZ DE DIzER
 QUANTOS VALORES 
 E QUAL O MAIOR NUMERO
 DEVE RECONHECER QUANDO NENHUM VALOR FOI PASSADO 
 ---- OUVE MUDANÇA COM A ADD DO FLUSH NA VERSAO, ESTA NA RESPOSTA.

100 FACA UM PROGRAMA QUE TENHA CHAMADA LISTA E DUAS FUNÇOES;
SORTEIA E SOMAPar
a primeira sorteia 5 primeiros e poem em lista
a segnda soma todas os pares sorteados pela anterior
'''