'''
101 CRIE UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO E DIGA SE ELA PODE VOTAR
SE É OBRIGATORIO
SE É OPCIONAL
SE NAO VOTA
* RETORNO DA FUNÇÃO DEVE SER LITERAL --ESCOPO DE IMPORTAÇAO-

102 ESCREVA UMA FUNÇAO FATORIAL
COM FUNÇAO DE FATORIAL
E COM PAAMETRO ****SHOW**** (MOSTRA O PROCESSO DE CALCUOO)
O PARAMETRO SHOW DEVE SER OPCIONAL

103 FUNÇAO CHAADA FICHA
NOME E NUMERO DE GOLS
DEVEE SER CAPAZ DE MOSTRAR OS DADOS MESMO QUE FALTE ALGUM PARAMETRO (SEM APRESENTAR ERROS)
*** CASO NAO TENHA PARAMETRO USE NOE DESCONHECIDO**

104 FUNÇAO LEIAINT() E CASO SEJA DIGITADO OUTRA COISA QUE NAO NUMERAL
NAO PERMITA AVANÇO ATE QUE NUMERO SEJA DIGITADO

105 LEIA NOTAS
RETORNE DICIONARIO COM NOTA
MAIOR
MENOR
TOTAL DE NOTAS
MEDIA DA GALERA
SITUAÇAO **** SIT=TRUE *** DEVE APARECER E VARIAR CONFORME A MEDIA
EM REPROVADO APROVADO E RECPERAÇAO

106 MINI SISTEMA QUE USE O INTERECTIVEHELP DO PTHON
O USUARIO DIGITA O COMANDO E O SISTEMA DEVE APARECER
QUANDO DIGITADO A PARALAVRA'FIM' O SISTEMA ACABA
USE CORES


'''