"""
6PROGAMA QUE LEIA VARIOS INTEIROS E PARA TERMINAR USE O 999
NO FIM MOSTRE A SOMA E QUANTOS FORAM DIGITADOS

67MOSTRE A TABUADA E EM SEGGUIDA OUTRA TABUADA DO NUMERO DIGITADO E PARA QUANDO POSTO
NUMERO NEGATIVO

68PROGRAMA QUE JOGUE PAROU IMPAR
É INTERROMPIDO QUANDO O JOGADOR PERDER
MOSTRE QUANTAS VITORIAS O JOGADOR TEVE

69QUE lEIA A IDADE E SEXO DE VARIAS PESSOAS E A CADA PESSOA CADASTRADA O PROGRAMA DEVERA PERGUNTAR
SE QUER CONTINUAR OU NAO
O PROGRAMA DEVERA MOSTRAR
QUANTAS ESSOAS MAIORES DE 18
QUANTOS HOMENS
QUANTAS MULHERES MENORES QUE 20

70LEIA NOME E PREÇO DE VARIOS PRODUTOS E 
MOSTRE 
QUANTO VOCE GASTOU 
NOME DO PRODUTO MAIS BARATO
PERGUNTAR SE QUER CONTINUAR
PRODUTOS CUSTANDO MAIS QUE 1000

71SIMULE O FUNCIONAMENTO DE UM CAIXA 24HRS 
NO INICIO PERGUNTE O VALOR A SER SACADO 
O VALOR DAS CEDULAS 
MOSTRE QUANTAS CEDULAS E SEUS RESPECTIVOS VALORES




"""