'''
113 REESCREVA A FUNÇÃO LEIA INT DO 104
INCLUA AGORA A POSSIBILIDADE DE UM TIPO INVALIDO, NUMERO INVALIDO
INCLUA TAMBEM UM PARA NUMEOS REAIS (FLOAT) QUE FUINCIONE DA MESMA MANEIRA
TAMBEM DEVE FICAR COMO ZERO CASO O VALOR NAO SEJA DIGITADO(ENCERRAR)

114 CRIE UM COD QUE DIGA SE UM DETERMINADO SITE ESTA NO AR
SIT -PUDIM

115 CRIE UM PEQUENO SIS MODULARIZADO
QUE POSSIBILITE CADASTRAR OS DADOS DE PESSOAS
O SIS DEVE SALVAR AS PESSOAS CADASTRADAS
ELE DEVE TER DUAS OPÇÃO CADASTRAR E MOSTRAR O CADASTRO -SAIR COMO TERCEIRA


'''