'''
90 FACA UM PROGRAMA QUE LEIO NOME E MEDIA DE UM ALUNO
GARDANDO TBM A SITUAÇÃO EM UMA LISTA
NOME- MEDIA -SE TA APROVADO OU NAO

91 4 JOGADORES JOGAM DADO (ALEATORIO)
GUARDE EM DICIONARIO E PONHA EM ORDEM
MOSTRE A POSIÇÃO DE CADA JOGADOR (RANKING)

92 PROGRAMA QUE LEIA NOME ANO DE NASCIMENTO
E CARTEIRA DE TRABALHO CADASTRE COM A IDADE
GUARDE EM DICIONARIO -- SE A CARTEIRA FOR DIFERENTE DE ZERO O DICIONARIO RECEBERA O ANO DE CONTRATAÇAO
E O SALARIO, CALCULE E ACRESCENTE ALEM DA IDADE CM QUANTOS ANOS A PESSOA VAI SE APOSENTAR

93 GERENCIAMENTE DO JOGADOR DE FUTEBOL.
NOME DO JOGADOR - QUANTAS PARTIDAS - QTD DE GOLS.
GUARDE EM DICIONARIO
INCLUA TOTAIS E ETC

94 CRIE UM PROGRAMA QUE LEIA NOME DE VARIAS PESSOAS.
GUARDE OS DADOS*DE CADA EM UM DICIONARIO
E TODOS OS DICIONARIO EM UMA LISTA
MOSTRE
PESSOAS CADASTRADOS
MEDIA DE IDADE
LISTA COM TODAS AS MULHERES
LISTA COM PESSOAS COM IDADE ACIMA DA MEDIA

95 APRIMORE  O GERENCIAMENTO DOS JOGADORES
COMO NO BOLETIM DA AULA ANTERIOR

'''