"""
57LEO O SEXO DE UMA PESSOAS E SO ACEITE  ME F CASO ERRADO PESSA
NOVAMENTE ATE O VALOR CORRETO

58GENIO  MAS DESSA VEZ O JOGADOR TENTAN ATE ACERTAR
MOSTRANDO QUANTOS PALPITES FORAM NESCESSARIOS PARA VENCER

59 QUE LEIA DOIS VALORES E MOSTRE UM MENu NA TELA
- SOMA- MULTIPLICAR- DIVIDIR - MAIOR- NOVOS NUMEROS -SAIR

60 LEIA UM NUMERO E MOSTRE O SEU FATORIAL

61 REFAÇA O 51 - LEIA  O PRIMEIRO TERMO E FAÇA UMA RAZAO DE UMA PA

62  CONINUAÇAO DO 61 - PERGUNTE SE QUER CONTINUAR A VER TERMOS

63 MOSTRE A SEQUENCIA FIBONACCI DE X

64 LEIA VARIOS NUMEROS INTEIROS E PARE APENS QUANDO FOR DIGITADO 999
MOSTRE A SOMA DE TODOS, MENOS O FLAG

65 LEIA VARIOS NUMEROS INTEIROS  VARIOS NUMEROS INT MOSTRE A SOMA DELES A MEDIA MAIOR MENOR
PERGUNTE SE O USUARIO QEER CONTINUAR

66
"""
