"""
46 FÇA UM PROGRAMA QUE MOSTRE A CONTAGEM REGRESSIVA PARA QUEIMA DE FOGOS
DE 0 Á 10 SALTO 1

47 CRIE UM PROGRAMA QUE MOSTRE TODOS OS NUMEROS PARES NO INTERVALO ENTRE 1 E 50

48 UM PROGRAMA QUE MOSTRE A SOMA DE TODOS OS NUMEROS IMPARES QUE SAO MULTIPLOS DE 3
NO INTERVALO DE 1 Á 500

49 REFAÇA O EXERCICIO 9. TABUADA

50 DESENVOLVA UM PROGRAMA QUE LEIA 6 NUMEROS INTEIROS E MOSTRE A SOMA DOS NUMEROS PARES

51 DESENVOLVA UM PROGRAMA QUE LEIA O PRIMEIRO TERMO E A RAZAO DE UMA PA ( PROGRESSAO ARITIMETICA)
MOSTRE OS 10 PRIMEIROS TERMOS DESTA PROGRESSAO

52 MOSTRE UM PROGRAMA QUE LEIA  UM UM NUMERO E DIGA SE ELE É OU NAO NUMERO PRIMO

53 CRIE UMA FRASE QUALQUER E DIGA SE ELA É UM PALINDROMO

54 CRIE UM PROGRAMA QUE LEIA A DATA DE NASCIMENTO DE 7 PESSOAS
E MOSTRE QUANTAS JA ATINGIRAM A MAIOR IDADE E QUANTAS NAO

55 PROGRAMA QUE LEIA UM PESO DE 5 PESSOAS E DIGA QUAL É O MAIOR E O MENOS PESOS LIDOS

56 PROGRAMA QUE LEIA NIME IDADE E SEXO E 4 PESSOAS. NO FINAL  MOSTRE
- A MEDIA DE IDADE
- QUAL NOME DO HOMEN MAIS VELHO
- QUANTAS MULHERES TEM MENOS DE 20 ANOS
"""